version: '3'
services:
  postgres-test:
    container_name: gnosis-postgres-test-1
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gnosis_test_db
    ports:
      - "5433:5432"  # Different port from main DB to avoid conflicts
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data: 